source 'https://rubygems.org'

gem 'rake', '~> 10.5.0'

# Assumes you want to run tests in the container, normally this would be in the dev group
gem 'rspec', '~> 3.4.0'
gem 'rubocop', '~> 0.38.0'

group :development do
  gem 'pry', '~> 0.10.3'
  gem 'yard', '~> 0.8.7.6'
  gem 'simplecov', '~> 0.11.2'
end

